name: API Test Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger
  push:
    branches: [ main ]    # Runs on push to main branch

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run Tests
      run: mvn clean test
    
    - name: Package for Octopus
      run: |
        $version="1.0.${{ github.run_number }}"
        Compress-Archive -Path * -DestinationPath "ApiTests.$version.zip"
    
    - name: Push to Octopus Cloud
      uses: OctopusDeploy/push-package-action@v3
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        server: ${{ secrets.OCTOPUS_SERVER_URL }}
        package: "ApiTests.${{ github.run_number }}.zip"
    
    - name: Create Octopus Release
      uses: OctopusDeploy/create-release-action@v3
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        server: ${{ secrets.OCTOPUS_SERVER_URL }}
        project: "API Tests"
        deploy_to: "Development"
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/
    
    - name: Send Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: API Test Results - ${{ github.repository }}
        to: ${{ secrets.MAIL_RECIPIENTS }}
        from: GitHub Actions
        body: |
          Test execution completed.
          See results at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        attachments: target/surefire-reports/*.html
